name: CI

on: [push, pull_request]

jobs:
  build:
    name: ${{ matrix.config.name }}
    runs-on: ${{ matrix.config.os }}
    strategy:
      fail-fast: false
      matrix:
        config:
        - {
            name: "Windows Latest - MSVC", artifact: "learn-cmake-msvc.tar.xz",
            os: windows-latest,
            build_type: "Release", cc: "cl", cxx: "cl"
          }
        - {
            name: "Ubuntu Latest - GCC", artifact: "learn-cmake-gcc.tar.xz",
            os: ubuntu-latest,
            build_type: "Release", cc: "gcc", cxx: "g++"
          }
        - {
            name: "Ubuntu Latest - Clang", artifact: "learn-cmake-clang.tar.xz",
            os: ubuntu-latest,
            build_type: "Release", cc: "clang", cxx: "clang++"
          }
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: 'recursive'
      - name: Set Windows ENV
        if: runner.os == 'Windows'
        uses: ilammy/msvc-dev-cmd@v1
      - name: Install Linux Dependencies
        if: runner.os == 'Linux'
        run: sudo apt install libxcursor-dev libxrandr-dev libxinerama-dev libxi-dev libglew-dev
      - name: CMake Configure 
        run: cmake -Bbuild -DCMAKE_BUILD_TYPE=${{ matrix.config.build_type }} -DCMAKE_C_COMPILER=${{ matrix.config.cc }} -DCMAKE_CXX_COMPILER=${{ matrix.config.cxx }}
      - name: CMake Build
        run: cmake --build build